[package]
name = "alloy-merkle-tree"
description = "Minimal Merkle Tree implementation"
license = "Apache-2.0"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/rkdud007/alloy-merkle-tree"
keywords = ["merkle", "tree", "merkle-tree"]
categories = ["cryptography", "data-structures", "blockchain"]
exclude = [".github"]
version = "0.5.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.6.2", default-features = false }
alloy-dyn-abi = { version = "0.6.2", default-features = false }
hashbrown = "0.14.3"
anyhow = "1.0"
