[package]
name = "alloy-merkle-tree"
license = "Apache-2.0"
license-file = "LICENSE"
repository = "https://github.com/rkdud007/alloy-merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = { version = "0.6.2" }
